import { useState } from 'react';
import { Button } from './ui/button';
import { Badge } from './ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from './ui/tabs';
import { Progress } from './ui/progress';
import { 
  Upload,
  FileSpreadsheet,
  PieChart,
  TrendingUp,
  Download,
  Eye,
  BarChart3,
  DollarSign,
  Clock,
  Shield,
  Zap,
  FileText,
  Briefcase,
  Target,
  Users,
  AlertCircle,
  CheckCircle,
  ArrowUpRight,
  ArrowDownRight,
  RefreshCw
} from 'lucide-react';

export default function PortfolioDemo() {
  const [uploadedFile, setUploadedFile] = useState<File | null>(null);
  const [analysisComplete, setAnalysisComplete] = useState(false);
  const [generatingReport, setGeneratingReport] = useState(false);
  const [portfolioData, setPortfolioData] = useState<any>(null);

  const samplePortfolio = {
    totalValue: 2450000,
    positions: [
      { symbol: 'AAPL', name: 'Apple Inc.', shares: 1000, price: 175.50, value: 175500, allocation: 7.2, tokenizable: true },
      { symbol: 'MSFT', name: 'Microsoft Corp.', shares: 800, price: 380.25, value: 304200, allocation: 12.4, tokenizable: true },
      { symbol: 'GOOGL', name: 'Alphabet Inc.', shares: 500, price: 140.75, value: 70375, allocation: 2.9, tokenizable: true },
      { symbol: 'TSLA', name: 'Tesla Inc.', shares: 600, price: 242.50, value: 145500, allocation: 5.9, tokenizable: true },
      { symbol: 'NVDA', name: 'NVIDIA Corp.', shares: 300, price: 895.00, value: 268500, allocation: 11.0, tokenizable: true },
      { symbol: 'SPY', name: 'SPDR S&P 500 ETF', shares: 2000, price: 485.75, value: 971500, allocation: 39.7, tokenizable: false },
      { symbol: 'BND', name: 'Vanguard Bond ETF', shares: 5000, price: 75.20, value: 376000, allocation: 15.3, tokenizable: false },
      { symbol: 'VTI', name: 'Vanguard Total Stock', shares: 800, price: 235.50, value: 188400, allocation: 7.7, tokenizable: false }
    ],
    analytics: {
      tokenizableValue: 964075,
      tokenizablePercentage: 39.3,
      averageSettlementTime: '2.3 days',
      potentialSavings: 47500,
      liquidityImprovement: '340%',
      fractionalAccess: true,
      complianceScore: 94.2
    }
  };

  const handleFileUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      setUploadedFile(file);
      // Simulate file processing
      setTimeout(() => {
        setPortfolioData(samplePortfolio);
        setAnalysisComplete(true);
      }, 2000);
    }
  };

  const handleDemoData = () => {
    setUploadedFile(new File(["demo"], "demo-portfolio.csv"));
    setTimeout(() => {
      setPortfolioData(samplePortfolio);
      setAnalysisComplete(true);
    }, 1000);
  };

  const generateReport = async () => {
    setGeneratingReport(true);
    
    // Simulate report generation
    await new Promise(resolve => setTimeout(resolve, 3000));
    
    setGeneratingReport(false);
    
    // Trigger download (in real app, this would be a PDF blob)
    const element = document.createElement('a');
    element.href = 'data:text/plain;charset=utf-8,Sample Tokenization Report - Generated by ChainSim Portfolio Copilot';
    element.download = 'tokenization-analysis-report.pdf';
    element.click();
  };

  const tokenizationScenarios = [
    {
      name: 'Conservative Approach',
      description: 'Tokenize only blue-chip individual stocks',
      tokenizedValue: 964075,
      percentage: 39.3,
      benefits: ['Faster settlement', 'Reduced counterparty risk', 'Enhanced liquidity'],
      risks: ['Technology adoption', 'Regulatory uncertainty']
    },
    {
      name: 'Moderate Approach', 
      description: 'Include select ETFs with tokenization capability',
      tokenizedValue: 1435575,
      percentage: 58.6,
      benefits: ['Diversified exposure', 'Fractional trading', '24/7 markets'],
      risks: ['Platform dependency', 'Custody considerations']
    },
    {
      name: 'Aggressive Approach',
      description: 'Maximum tokenization across all eligible assets',
      tokenizedValue: 1811575,
      percentage: 73.9,
      benefits: ['Maximum efficiency gains', 'Global accessibility', 'Programmable compliance'],
      risks: ['Higher complexity', 'Increased technology risk']
    }
  ];

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-900">
      <div className="p-6 lg:p-8 space-y-6">
        {/* Header */}
        <div className="bg-white dark:bg-slate-800 rounded-lg border border-slate-200 dark:border-slate-700 p-6">
          <div className="flex items-center justify-between">
            <div>
              <div className="flex items-center space-x-3 mb-2">
                <div className="w-8 h-8 bg-slate-900 dark:bg-slate-100 rounded-lg flex items-center justify-center">
                  <PieChart className="w-4 h-4 text-white dark:text-slate-900" />
                </div>
                <h1 className="text-2xl font-semibold text-slate-900 dark:text-slate-100">
                  Portfolio Analytics
                </h1>
              </div>
              <p className="text-slate-600 dark:text-slate-400">
                Advanced portfolio analysis and tokenization modeling for institutional clients
              </p>
            </div>
            
            <div className="flex items-center space-x-3">
              <div className="flex items-center space-x-2 px-3 py-1.5 bg-blue-50 dark:bg-blue-950/20 text-blue-700 dark:text-blue-400 rounded-md border border-blue-200 dark:border-blue-800">
                <Briefcase className="w-3 h-3" />
                <span className="text-sm font-medium">RIA Tool</span>
              </div>
              <Button variant="outline" size="sm" className="text-slate-600 dark:text-slate-400" onClick={handleDemoData}>
                <Eye className="w-4 h-4 mr-2" />
                Demo Data
              </Button>
            </div>
          </div>
        </div>

        {!analysisComplete ? (
          /* Upload Section */
          <div className="bg-white dark:bg-slate-800 rounded-lg border border-slate-200 dark:border-slate-700 p-8">
            <div className="max-w-2xl mx-auto text-center space-y-6">
              <div className="w-16 h-16 mx-auto bg-slate-100 dark:bg-slate-700 rounded-lg flex items-center justify-center">
                <Upload className="w-8 h-8 text-slate-600 dark:text-slate-400" />
              </div>
              
              <div>
                <h2 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-2">
                  Portfolio Data Upload
                </h2>
                <p className="text-slate-600 dark:text-slate-400 max-w-md mx-auto">
                  Upload brokerage statements, CSV exports, or portfolio data for comprehensive tokenization analysis
                </p>
              </div>

              <div className="max-w-md mx-auto">
                <div className="border-2 border-dashed border-slate-300 dark:border-slate-600 rounded-lg p-8 hover:border-purple-400 transition-colors">
                  <input
                    type="file"
                    accept=".csv,.xlsx,.pdf"
                    onChange={handleFileUpload}
                    className="hidden"
                    id="portfolio-upload"
                  />
                  <label
                    htmlFor="portfolio-upload"
                    className="cursor-pointer block text-center space-y-3"
                  >
                    <FileSpreadsheet className="w-8 h-8 mx-auto text-slate-400" />
                    <div>
                      <p className="font-medium text-slate-900 dark:text-slate-100">
                        Click to upload or drag and drop
                      </p>
                      <p className="text-sm text-slate-600 dark:text-slate-400">
                        CSV, Excel, or PDF files up to 10MB
                      </p>
                    </div>
                  </label>
                </div>
                
                {uploadedFile && (
                  <div className="mt-4 p-4 bg-blue-50 dark:bg-blue-950/30 rounded-lg">
                    <div className="flex items-center space-x-3">
                      <FileSpreadsheet className="w-5 h-5 text-blue-600" />
                      <div className="flex-1">
                        <p className="font-medium text-blue-900 dark:text-blue-100">
                          {uploadedFile.name}
                        </p>
                        <p className="text-sm text-blue-600 dark:text-blue-400">
                          Processing portfolio data...
                        </p>
                      </div>
                      <RefreshCw className="w-4 h-4 text-blue-600 animate-spin" />
                    </div>
                    <Progress value={75} className="mt-3" />
                  </div>
                )}
              </div>

              <div className="grid grid-cols-3 gap-6 max-w-2xl mx-auto">
                <div className="text-center">
                  <div className="w-12 h-12 mx-auto bg-emerald-100 dark:bg-emerald-950/30 rounded-lg flex items-center justify-center mb-3">
                    <Shield className="w-6 h-6 text-emerald-600" />
                  </div>
                  <h3 className="font-semibold text-slate-900 dark:text-slate-100 mb-2">
                    Secure Processing
                  </h3>
                  <p className="text-sm text-slate-600 dark:text-slate-400">
                    Data encrypted and processed locally
                  </p>
                </div>
                
                <div className="text-center">
                  <div className="w-12 h-12 mx-auto bg-blue-100 dark:bg-blue-950/30 rounded-lg flex items-center justify-center mb-3">
                    <Zap className="w-6 h-6 text-blue-600" />
                  </div>
                  <h3 className="font-semibold text-slate-900 dark:text-slate-100 mb-2">
                    AI Normalization
                  </h3>
                  <p className="text-sm text-slate-600 dark:text-slate-400">
                    Automatic format recognition
                  </p>
                </div>
                
                <div className="text-center">
                  <div className="w-12 h-12 mx-auto bg-purple-100 dark:bg-purple-950/30 rounded-lg flex items-center justify-center mb-3">
                    <Target className="w-6 h-6 text-purple-600" />
                  </div>
                  <h3 className="font-semibold text-slate-900 dark:text-slate-100 mb-2">
                    Smart Analysis
                  </h3>
                  <p className="text-sm text-slate-600 dark:text-slate-400">
                    Tokenization potential scoring
                  </p>
                </div>
              </div>
            </div>
          </div>
        ) : (
          /* Analysis Results */
          <div className="space-y-8">
            {/* Portfolio Overview */}
            <div className="grid grid-cols-4 gap-6">
              <div className="bg-white dark:bg-slate-800 rounded-lg border border-slate-200 dark:border-slate-700 p-6">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-2xl font-bold text-slate-900 dark:text-slate-100">
                      ${portfolioData.totalValue.toLocaleString()}
                    </p>
                    <p className="text-sm text-slate-500 dark:text-slate-400">Total Portfolio Value</p>
                  </div>
                  <div className="w-10 h-10 bg-slate-100 dark:bg-slate-700 rounded-lg flex items-center justify-center">
                    <DollarSign className="w-5 h-5 text-slate-600 dark:text-slate-400" />
                  </div>
                </div>
              </div>
              
              <div className="bg-white dark:bg-slate-800 rounded-lg border border-slate-200 dark:border-slate-700 p-6">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-2xl font-bold text-slate-900 dark:text-slate-100">
                      ${portfolioData.analytics.tokenizableValue.toLocaleString()}
                    </p>
                    <p className="text-sm text-slate-500 dark:text-slate-400">Tokenizable Assets</p>
                  </div>
                  <div className="w-10 h-10 bg-slate-100 dark:bg-slate-700 rounded-lg flex items-center justify-center">
                    <TrendingUp className="w-5 h-5 text-emerald-600" />
                  </div>
                </div>
              </div>
              
              <div className="bg-white dark:bg-slate-800 rounded-lg border border-slate-200 dark:border-slate-700 p-6">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-2xl font-bold text-slate-900 dark:text-slate-100">
                      {portfolioData.analytics.averageSettlementTime}
                    </p>
                    <p className="text-sm text-slate-500 dark:text-slate-400">Current Settlement</p>
                  </div>
                  <div className="w-10 h-10 bg-slate-100 dark:bg-slate-700 rounded-lg flex items-center justify-center">
                    <Clock className="w-5 h-5 text-slate-600 dark:text-slate-400" />
                  </div>
                </div>
              </div>
              
              <div className="bg-white dark:bg-slate-800 rounded-lg border border-slate-200 dark:border-slate-700 p-6">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-2xl font-bold text-slate-900 dark:text-slate-100">
                      {portfolioData.analytics.complianceScore}%
                    </p>
                    <p className="text-sm text-slate-500 dark:text-slate-400">Compliance Score</p>
                  </div>
                  <div className="w-10 h-10 bg-slate-100 dark:bg-slate-700 rounded-lg flex items-center justify-center">
                    <Target className="w-5 h-5 text-slate-600 dark:text-slate-400" />
                  </div>
                </div>
              </div>
            </div>

            {/* Main Analysis Interface */}
            <Tabs defaultValue="holdings" className="space-y-6">
              <TabsList className="grid w-full grid-cols-4">
                <TabsTrigger value="holdings">Holdings Analysis</TabsTrigger>
                <TabsTrigger value="scenarios">Tokenization Scenarios</TabsTrigger>
                <TabsTrigger value="benefits">Benefits Analysis</TabsTrigger>
                <TabsTrigger value="reports">Generate Reports</TabsTrigger>
              </TabsList>

              <TabsContent value="holdings" className="space-y-6">
                <div className="bg-white dark:bg-slate-800 rounded-lg border border-slate-200 dark:border-slate-700 p-6">
                  <div className="flex items-center justify-between mb-6">
                    <h3 className="text-xl font-bold text-slate-900 dark:text-slate-100">
                      Portfolio Holdings
                    </h3>
                    <div className="flex items-center space-x-2">
                      <Badge className="bg-emerald-100 text-emerald-700">
                        {portfolioData.positions.filter((p: any) => p.tokenizable).length} Tokenizable
                      </Badge>
                      <Badge className="bg-slate-100 text-slate-700">
                        {portfolioData.positions.filter((p: any) => !p.tokenizable).length} Traditional
                      </Badge>
                    </div>
                  </div>

                  <div className="space-y-4">
                    {portfolioData.positions.map((position: any, index: number) => (
                      <div key={index} className="p-4 border border-slate-200 dark:border-slate-700 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors">
                        <div className="flex items-center justify-between">
                          <div className="flex items-center space-x-4">
                            <div className={`w-10 h-10 rounded-lg flex items-center justify-center ${
                              position.tokenizable 
                                ? 'bg-emerald-100 dark:bg-emerald-950/30' 
                                : 'bg-slate-100 dark:bg-slate-800'
                            }`}>
                              {position.tokenizable ? (
                                <CheckCircle className="w-5 h-5 text-emerald-600" />
                              ) : (
                                <AlertCircle className="w-5 h-5 text-slate-500" />
                              )}
                            </div>
                            
                            <div>
                              <p className="font-semibold text-slate-900 dark:text-slate-100">
                                {position.symbol}
                              </p>
                              <p className="text-sm text-slate-600 dark:text-slate-400">
                                {position.name}
                              </p>
                            </div>
                          </div>
                          
                          <div className="text-right space-y-1">
                            <div className="flex items-center space-x-4">
                              <div className="text-right">
                                <p className="font-semibold text-slate-900 dark:text-slate-100">
                                  {position.shares.toLocaleString()} shares
                                </p>
                                <p className="text-sm text-slate-600 dark:text-slate-400">
                                  @ ${position.price}
                                </p>
                              </div>
                              
                              <div className="text-right">
                                <p className="font-bold text-slate-900 dark:text-slate-100">
                                  ${position.value.toLocaleString()}
                                </p>
                                <p className="text-sm text-slate-600 dark:text-slate-400">
                                  {position.allocation}% allocation
                                </p>
                              </div>
                              
                              <div className="w-20">
                                {position.tokenizable ? (
                                  <Badge className="bg-emerald-100 text-emerald-700 w-full justify-center">
                                    Ready
                                  </Badge>
                                ) : (
                                  <Badge className="bg-slate-100 text-slate-700 w-full justify-center">
                                    N/A
                                  </Badge>
                                )}
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </TabsContent>

              <TabsContent value="scenarios" className="space-y-6">
                <div className="grid gap-6">
                  {tokenizationScenarios.map((scenario, index) => (
                    <div key={index} className="bg-white dark:bg-slate-800 rounded-lg border border-slate-200 dark:border-slate-700 p-6">
                      <div className="space-y-4">
                        <div className="flex items-start justify-between">
                          <div>
                            <h3 className="text-xl font-bold text-slate-900 dark:text-slate-100">
                              {scenario.name}
                            </h3>
                            <p className="text-slate-600 dark:text-slate-400 mt-1">
                              {scenario.description}
                            </p>
                          </div>
                          
                          <div className="text-right">
                            <p className="text-2xl font-bold text-slate-900 dark:text-slate-100">
                              ${scenario.tokenizedValue.toLocaleString()}
                            </p>
                            <p className="text-sm text-slate-600 dark:text-slate-400">
                              {scenario.percentage}% of portfolio
                            </p>
                          </div>
                        </div>
                        
                        <div className="grid md:grid-cols-2 gap-6">
                          <div>
                            <h4 className="font-semibold text-slate-900 dark:text-slate-100 mb-3 flex items-center">
                              <ArrowUpRight className="w-4 h-4 text-emerald-600 mr-2" />
                              Benefits
                            </h4>
                            <ul className="space-y-2">
                              {scenario.benefits.map((benefit, benefitIndex) => (
                                <li key={benefitIndex} className="flex items-center space-x-2">
                                  <CheckCircle className="w-4 h-4 text-emerald-600" />
                                  <span className="text-sm text-slate-700 dark:text-slate-300">
                                    {benefit}
                                  </span>
                                </li>
                              ))}
                            </ul>
                          </div>
                          
                          <div>
                            <h4 className="font-semibold text-slate-900 dark:text-slate-100 mb-3 flex items-center">
                              <ArrowDownRight className="w-4 h-4 text-orange-600 mr-2" />
                              Considerations
                            </h4>
                            <ul className="space-y-2">
                              {scenario.risks.map((risk, riskIndex) => (
                                <li key={riskIndex} className="flex items-center space-x-2">
                                  <AlertCircle className="w-4 h-4 text-orange-600" />
                                  <span className="text-sm text-slate-700 dark:text-slate-300">
                                    {risk}
                                  </span>
                                </li>
                              ))}
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </TabsContent>

              <TabsContent value="benefits" className="space-y-6">
                <div className="grid md:grid-cols-2 gap-6">
                  <div className="bg-white dark:bg-slate-800 rounded-lg border border-slate-200 dark:border-slate-700 p-6">
                    <h3 className="text-xl font-bold text-slate-900 dark:text-slate-100 mb-6">
                      Efficiency Gains
                    </h3>
                    
                    <div className="space-y-6">
                      <div>
                        <div className="flex justify-between mb-2">
                          <span className="text-slate-600 dark:text-slate-400">Settlement Speed</span>
                          <span className="font-semibold text-slate-900 dark:text-slate-100">2.3 days → T+0</span>
                        </div>
                        <div className="w-full bg-slate-200 dark:bg-slate-700 rounded-full h-2">
                          <div className="bg-emerald-600 h-2 rounded-full" style={{width: '95%'}}></div>
                        </div>
                        <p className="text-sm text-emerald-600 mt-1">95% faster settlement</p>
                      </div>
                      
                      <div>
                        <div className="flex justify-between mb-2">
                          <span className="text-slate-600 dark:text-slate-400">Liquidity Access</span>
                          <span className="font-semibold text-slate-900 dark:text-slate-100">+340%</span>
                        </div>
                        <div className="w-full bg-slate-200 dark:bg-slate-700 rounded-full h-2">
                          <div className="bg-blue-600 h-2 rounded-full" style={{width: '85%'}}></div>
                        </div>
                        <p className="text-sm text-blue-600 mt-1">24/7 trading capability</p>
                      </div>
                      
                      <div>
                        <div className="flex justify-between mb-2">
                          <span className="text-slate-600 dark:text-slate-400">Cost Savings</span>
                          <span className="font-semibold text-slate-900 dark:text-slate-100">$47,500/year</span>
                        </div>
                        <div className="w-full bg-slate-200 dark:bg-slate-700 rounded-full h-2">
                          <div className="bg-purple-600 h-2 rounded-full" style={{width: '70%'}}></div>
                        </div>
                        <p className="text-sm text-purple-600 mt-1">Reduced operational costs</p>
                      </div>
                    </div>
                  </div>
                  
                  <div className="bg-white dark:bg-slate-800 rounded-lg border border-slate-200 dark:border-slate-700 p-6">
                    <h3 className="text-xl font-bold text-slate-900 dark:text-slate-100 mb-6">
                      Client Benefits
                    </h3>
                    
                    <div className="space-y-4">
                      <div className="flex items-start space-x-3">
                        <div className="w-8 h-8 bg-emerald-100 dark:bg-emerald-950/30 rounded-lg flex items-center justify-center mt-1">
                          <Zap className="w-4 h-4 text-emerald-600" />
                        </div>
                        <div>
                          <h4 className="font-semibold text-slate-900 dark:text-slate-100">
                            Fractional Ownership
                          </h4>
                          <p className="text-sm text-slate-600 dark:text-slate-400">
                            Enable smaller investors to access high-value assets
                          </p>
                        </div>
                      </div>
                      
                      <div className="flex items-start space-x-3">
                        <div className="w-8 h-8 bg-blue-100 dark:bg-blue-950/30 rounded-lg flex items-center justify-center mt-1">
                          <Shield className="w-4 h-4 text-blue-600" />
                        </div>
                        <div>
                          <h4 className="font-semibold text-slate-900 dark:text-slate-100">
                            Enhanced Security
                          </h4>
                          <p className="text-sm text-slate-600 dark:text-slate-400">
                            Blockchain-based custody and programmable compliance
                          </p>
                        </div>
                      </div>
                      
                      <div className="flex items-start space-x-3">
                        <div className="w-8 h-8 bg-purple-100 dark:bg-purple-950/30 rounded-lg flex items-center justify-center mt-1">
                          <Users className="w-4 h-4 text-purple-600" />
                        </div>
                        <div>
                          <h4 className="font-semibold text-slate-900 dark:text-slate-100">
                            Global Access
                          </h4>
                          <p className="text-sm text-slate-600 dark:text-slate-400">
                            Cross-border trading without traditional barriers
                          </p>
                        </div>
                      </div>
                      
                      <div className="flex items-start space-x-3">
                        <div className="w-8 h-8 bg-orange-100 dark:bg-orange-950/30 rounded-lg flex items-center justify-center mt-1">
                          <BarChart3 className="w-4 h-4 text-orange-600" />
                        </div>
                        <div>
                          <h4 className="font-semibold text-slate-900 dark:text-slate-100">
                            Real-time Reporting
                          </h4>
                          <p className="text-sm text-slate-600 dark:text-slate-400">
                            Instant portfolio updates and transparent fee structure
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </TabsContent>

              <TabsContent value="reports" className="space-y-6">
                <div className="bg-white dark:bg-slate-800 rounded-lg border border-slate-200 dark:border-slate-700 p-6">
                  <div className="text-center space-y-6">
                    <div className="w-20 h-20 mx-auto bg-slate-100 dark:bg-slate-700 rounded-lg flex items-center justify-center">
                      <FileText className="w-10 h-10 text-slate-600 dark:text-slate-400" />
                    </div>
                    
                    <div>
                      <h2 className="text-2xl font-bold text-slate-900 dark:text-slate-100 mb-3">
                        Generate Client Report
                      </h2>
                      <p className="text-slate-600 dark:text-slate-400 max-w-md mx-auto">
                        Create a professional PDF report with tokenization analysis, scenarios, and recommendations for your clients
                      </p>
                    </div>
                    
                    <Button 
                      onClick={generateReport}
                      disabled={generatingReport}
                      size="lg"
                      className="bg-slate-900 hover:bg-slate-800 text-white dark:bg-slate-100 dark:hover:bg-slate-200 dark:text-slate-900"
                    >
                      {generatingReport ? (
                        <>
                          <RefreshCw className="w-5 h-5 mr-2 animate-spin" />
                          Generating Report...
                        </>
                      ) : (
                        <>
                          <Download className="w-5 h-5 mr-2" />
                          Generate PDF Report
                        </>
                      )}
                    </Button>
                    
                    {generatingReport && (
                      <div className="max-w-md mx-auto">
                        <Progress value={65} className="mb-2" />
                        <p className="text-sm text-slate-600 dark:text-slate-400">
                          Analyzing tokenization scenarios and generating insights...
                        </p>
                      </div>
                    )}
                  </div>
                </div>
              </TabsContent>
            </Tabs>
          </div>
        )}
      </div>
    </div>
  );
}